# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeProject
  pod 'RNMobileCenterShared', '~> 0.9.0'
  pod 'MobileCenter/Analytics', '~> 0.12.1'

  

  target 'AwesomeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AwesomeProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeProject-tvOS

  target 'AwesomeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
